export const posts = [
  {
    slug: 'what-is-geo',
    tag: 'Guide',
    tagColor: '#c8956c',
    title: 'What Is Generative Engine Optimization (GEO)?',
    excerpt: 'GEO-optimized content achieves 30–115% higher visibility in AI-generated responses. Learn the discipline driving the next era of search.',
    readTime: '8 min read',
    date: 'June 2026',
    content: [
      { type: 'p', text: "Generative Engine Optimization — or GEO — is the discipline of optimizing your brand's content, technical infrastructure, and authority signals so that large language models (LLMs) like ChatGPT, Google Gemini, Perplexity, and Microsoft Copilot cite and recommend your business in their AI-generated answers." },
      { type: 'p', text: "Traditional SEO was about earning a blue link on page one of Google. GEO is about earning a named recommendation inside the AI answer itself — before the user ever sees a link. When someone asks ChatGPT \"What's the best family law firm in Austin?\" or \"Which med spa near me is worth it?\", GEO is what determines whether AI says your name or your competitor's." },
      { type: 'h2', text: 'Why GEO Is Exploding Right Now' },
      { type: 'p', text: 'Over 40% of all searches now return AI-generated answers. ChatGPT has crossed 900 million weekly active users. Google AI Overviews appear on roughly 1.5 billion queries every month. Yet only 23% of marketers have invested a single dollar into GEO — which means the businesses that move now capture an enormous, largely uncontested visibility advantage.' },
      { type: 'stat', text: 'Academic research from Princeton University, Georgia Tech, and IIT Delhi found that GEO-optimized content achieves 30–115% higher visibility in AI-generated responses compared to unoptimized content.' },
      { type: 'h2', text: 'How GEO Differs from SEO' },
      { type: 'p', text: 'SEO optimizes for keyword ranking in a list of links. GEO optimizes for entity recognition in a paragraph of prose. The signals are fundamentally different:' },
      { type: 'list', items: [
        'SEO rewards backlinks. GEO rewards brand mentions on authoritative sources — and brand mentions show a 3× stronger correlation with AI citations.',
        'SEO rewards keyword density. GEO rewards answer-first content passages of 134–167 words that directly address a question.',
        'SEO rewards page authority. GEO rewards named experts with verifiable credentials (Person schema, LinkedIn profiles, published bylines).',
        'SEO rewards fast page load. GEO rewards AI crawler accessibility — GPTBot, Google-Extended, PerplexityBot must all be permitted in your robots.txt.',
      ]},
      { type: 'h2', text: 'The 5 Core Pillars of GEO' },
      { type: 'list', items: [
        'Content Restructuring — Rewrite your key pages with answer-first openings. Lead with the direct answer in the first paragraph, not a preamble.',
        'JSON-LD Schema Markup — Implement Organization, LocalBusiness, FAQPage, HowTo, and Person schema so AI models can parse your entities with confidence.',
        'AI Crawler Access — Audit your robots.txt and ensure GPTBot, Google-Extended, PerplexityBot, and ClaudeBot can access your site.',
        'Brand Authority Building — Build consistent mentions across Google Business Profile, industry directories, Crunchbase, LinkedIn, and local media.',
        'GEO Score Monitoring — Track your AI citation rate monthly across platforms and refine based on which query types you\'re winning or losing.',
      ]},
      { type: 'h2', text: 'What to Expect on the Timeline' },
      { type: 'list', items: [
        'Days 1–30: Technical foundation — schema, crawler access, site structure.',
        'Days 30–90: Content restructuring and first AI mentions appear.',
        'Months 3–6: Measurable GEO score improvements across platforms.',
        'Months 6–12: Compounding growth as authority signals compound.',
      ]},
      { type: 'p', text: 'GEO is not a one-time fix. It is a compounding discipline — the brands that start building now will own the AI search landscape by 2027.' },
    ],
  },
  {
    slug: 'how-to-rank-on-chatgpt',
    tag: 'Playbook',
    tagColor: '#8b9e7a',
    title: 'How to Rank on ChatGPT in 2026: 7-Step Guide for Businesses',
    excerpt: "Brand mentions on authoritative sources show 3× stronger correlation with AI citations than backlinks. Here's the full framework.",
    readTime: '7 min read',
    date: 'June 2026',
    content: [
      { type: 'p', text: 'To rank on ChatGPT means getting your business recommended by name when users ask it questions about your category, location, or service. ChatGPT does not use a ranking list — it synthesizes information from its training data and, increasingly, from live web browsing. Here is the 7-step system that consistently produces results.' },
      { type: 'h2', text: 'The Short Answer' },
      { type: 'stat', text: 'Enable GPTBot in your robots.txt, implement LocalBusiness and FAQPage schema, restructure your content into answer-first passages of 134–167 words, and earn brand mentions across Google Business Profile, industry directories, and authoritative blogs.' },
      { type: 'h2', text: 'Step 1 — Enable GPTBot Access' },
      { type: 'p', text: 'Open your robots.txt file and confirm you are not blocking GPTBot, PerplexityBot, Google-Extended, or ClaudeBot. Many sites accidentally block these crawlers through wildcard disallow rules. If ChatGPT cannot crawl your site, it cannot cite it.' },
      { type: 'h2', text: 'Step 2 — Implement JSON-LD Schema' },
      { type: 'p', text: 'Add LocalBusiness schema with your full NAP (name, address, phone), business category, service area, and opening hours. Add FAQPage schema to any page with questions and answers. Add Person schema for your founder or lead expert. Pages with valid JSON-LD are 3.6× more likely to appear in AI-generated answers.' },
      { type: 'h2', text: 'Step 3 — Restructure Content Answer-First' },
      { type: 'p', text: 'ChatGPT cites content that answers the question immediately. Rewrite your key service pages so the very first paragraph contains a direct, complete answer to the most common question about that service. Keep these answer blocks between 134 and 167 words — research shows this length is cited 2.1× more frequently than longer passages.' },
      { type: 'h2', text: 'Step 4 — Add Named Sources and Statistics' },
      { type: 'p', text: 'AI models trust content that cites verifiable sources. Add statistics with source names and years. This signals credibility to the model and makes your content far more likely to be reproduced in an AI answer.' },
      { type: 'h2', text: 'Step 5 — Build Brand Authority Signals' },
      { type: 'list', items: [
        'Google Business Profile — complete every field, add photos, respond to reviews.',
        'Yelp and industry directories — consistent NAP across all listings.',
        'Local media — one local news mention is worth dozens of directory listings.',
        'LinkedIn — publish original thought-leadership posts monthly.',
        'Crunchbase — create and verify your company profile.',
      ]},
      { type: 'h2', text: 'Step 6 — Create a Named Expert Presence' },
      { type: 'p', text: 'ChatGPT trusts humans more than brands. Publish content under a named founder or expert, include their credentials in every bio, and link to their LinkedIn profile. Add Person schema with their name, job title, and affiliation. This dramatically increases the probability that AI will cite your content.' },
      { type: 'h2', text: 'Step 7 — Monitor and Iterate Monthly' },
      { type: 'p', text: "Run a monthly audit: ask ChatGPT 10–20 high-intent queries relevant to your business and location. Track which queries you appear on, which you miss, and how prominently you are mentioned. Use this data to prioritize your next month's content and authority-building work." },
      { type: 'p', text: 'Initial AI mentions typically appear within 60–90 days. Significant visibility improvement arrives in 4–6 months. Start today — your competitors are.' },
    ],
  },
  {
    slug: 'how-to-rank-in-google-ai-overviews',
    tag: 'Guide',
    tagColor: '#c8956c',
    title: 'How to Rank in Google AI Overviews (2026 Guide)',
    excerpt: "Pages with proper schema are 3.6× more likely to appear. AI Overviews reach 1.5B monthly users — here's how to get cited.",
    readTime: '6 min read',
    date: 'June 2026',
    content: [
      { type: 'p', text: 'Google AI Overviews appear at the top of search results — above all organic links — and reach approximately 1.5 billion users every month across 200+ countries. Being cited in an AI Overview is the highest-value placement in search today. Here is exactly how to earn it.' },
      { type: 'h2', text: 'The Short Answer' },
      { type: 'stat', text: "To rank in Google AI Overviews you need four things: a top-10 organic ranking for the query, strong E-E-A-T signals, correct schema markup, and 40–60 word answer blocks that directly respond to the user's question." },
      { type: 'h2', text: 'What Makes AI Overviews Different from ChatGPT' },
      { type: 'p', text: 'ChatGPT draws primarily from training data and browsing. Google AI Overviews draw from the live search index — which means traditional SEO ranking still matters. You generally need to rank in the top 10 organically for a query before Google will include you in its AI Overview for that query.' },
      { type: 'h2', text: 'The 7-Step Process' },
      { type: 'list', items: [
        'Allow Google-Extended — Confirm your robots.txt does not block Google-Extended, which is the specific crawler Google uses to build AI Overviews.',
        'Achieve top-10 organic rankings — Use traditional SEO (quality backlinks, on-page optimization, technical health) to rank for your target queries.',
        'Strengthen E-E-A-T — Add author bylines with credentials, cite reputable sources, display trust signals (awards, certifications, client logos), and keep content current.',
        'Write 40–60 word answer blocks — Immediately after each heading, include a concise paragraph that directly answers the question implied by that heading.',
        'Implement JSON-LD schema — Add Article, FAQPage, or HowTo schema depending on content type. Pages with proper schema are 3.6× more likely to appear.',
        'Optimize Core Web Vitals — Target LCP under 2.5s, INP under 200ms, CLS under 0.1.',
        'Monitor appearances monthly — Use Google Search Console and manual query testing to track which queries produce AI Overview appearances.',
      ]},
      { type: 'h2', text: 'Common Mistakes to Avoid' },
      { type: 'list', items: [
        'Blocking Google-Extended unintentionally via wildcard disallow rules.',
        'Burying the answer deep in the page instead of placing it immediately after the heading.',
        'Omitting author attribution — anonymous content receives far less trust weighting.',
        "Using invalid schema markup — validate everything with Google's Rich Results Test.",
        'Neglecting page speed — a slow page rarely earns AI Overview placement.',
      ]},
      { type: 'h2', text: 'Timeline' },
      { type: 'p', text: 'If you already rank in the top 10 organically, implementing the remaining steps typically produces AI Overview appearances within 2–4 weeks. Building from scratch takes 3–6 months. Start with content structure and schema immediately; they are the fastest wins.' },
    ],
  },
  {
    slug: 'ai-visibility-for-businesses',
    tag: 'Strategy',
    tagColor: '#7a8eb5',
    title: 'AI Visibility for Businesses: The Complete Guide',
    excerpt: 'Over 40% of searches now return AI-generated answers. Only 23% of marketers have invested — the gap is your opportunity.',
    readTime: '9 min read',
    date: 'June 2026',
    content: [
      { type: 'p', text: 'AI visibility means your business gets recommended by name inside AI-generated answers — not just listed in a search result. When someone asks ChatGPT, Google AI, or Perplexity about your service category and location, a business with strong AI visibility is the one the AI names. A business without it is invisible.' },
      { type: 'h2', text: 'Why AI Visibility Matters Right Now' },
      { type: 'p', text: "Over 40% of searches now produce AI-generated answers. ChatGPT's weekly active user count has crossed 900 million. Google AI Overviews reach 1.5 billion users monthly. Yet only 23% of marketers have made any investment in AI visibility — leaving a massive, largely uncontested opportunity." },
      { type: 'stat', text: 'AI-referred sessions grew 527% between January and May 2025, according to SparkToro. The businesses capturing that traffic are those with strong GEO signals already in place.' },
      { type: 'h2', text: 'The 5-Phase AI Visibility Framework' },
      { type: 'list', items: [
        'Phase 1: AI Visibility Audit — Test 40+ high-intent queries across ChatGPT, Perplexity, Google AI, Gemini, and Copilot. Establish your current GEO score (0–100) and identify specific gaps.',
        'Phase 2: Technical Foundation — Confirm AI crawler access (GPTBot, Google-Extended, PerplexityBot, ClaudeBot). Fix crawl blocks. Optimize site speed and mobile performance.',
        'Phase 3: Schema and Structured Data — Implement Organization, LocalBusiness, FAQPage, HowTo, and Person JSON-LD. Validate with Google\'s Rich Results Test.',
        'Phase 4: Content Restructuring — Rewrite key pages with answer-first openings. Add named expert attribution. Insert verified statistics with source citations.',
        'Phase 5: Brand Authority and Monitoring — Build consistent brand mentions across authoritative directories, local media, and industry publications. Monitor monthly.',
      ]},
      { type: 'h2', text: 'Industries Where AI Visibility Wins Are Largest' },
      { type: 'list', items: [
        'Law firms — "best personal injury attorney in [city]"',
        'Medical and cosmetic practices — "top med spa near me"',
        'Cosmetic dentistry — "best Invisalign provider in [city]"',
        'Real estate — "top real estate agent in [neighborhood]"',
        'Luxury home services — "most trusted home renovation contractor near me"',
      ]},
      { type: 'h2', text: 'Pricing and Timeline' },
      { type: 'p', text: 'Most businesses see measurable AI visibility improvements within 60–90 days. Significant gains typically arrive within 4–6 months. Our done-for-you AI visibility program starts at $2,000 setup plus $500/month, and includes monthly GEO score reporting, platform-specific optimization, and dedicated strategy support.' },
    ],
  },
  {
    slug: 'how-to-get-recommended-by-chatgpt',
    tag: 'Playbook',
    tagColor: '#8b9e7a',
    title: 'How to Get Recommended by ChatGPT',
    excerpt: 'Consistent brand mentions, answer-first content, and JSON-LD schema are the three pillars. We break down exactly how to build each.',
    readTime: '6 min read',
    date: 'June 2026',
    content: [
      { type: 'p', text: "Getting recommended by ChatGPT is no longer an accident. It is an engineered outcome — and the businesses that understand how ChatGPT decides what to recommend are the ones consistently appearing in its answers. Here is the complete playbook." },
      { type: 'h2', text: 'How ChatGPT Decides What to Recommend' },
      { type: 'p', text: "ChatGPT builds recommendations from two sources: its training data and, for ChatGPT with browsing enabled, live web content. Your brand needs to exist credibly in both — in the authoritative sources that informed the model's training, and on web pages the model can cite today." },
      { type: 'p', text: 'The four factors that most strongly predict a ChatGPT recommendation are: consistent brand mentions on authoritative domains, structured data (JSON-LD schema) on your website, AI crawler access via robots.txt, and content written in answer-first format.' },
      { type: 'h2', text: 'Pillar 1 — Brand Mentions on Authoritative Sources' },
      { type: 'p', text: 'Brand mentions on authoritative sources correlate 3× more strongly with ChatGPT citations than backlinks alone. The key sources to target:' },
      { type: 'list', items: [
        'Google Business Profile — the single most important entity signal. Complete every field.',
        'Yelp, Healthgrades, Avvo, Houzz (depending on your industry) — category-specific directories.',
        'Local news outlets — even one mention in a regional publication carries significant weight.',
        'LinkedIn company page — publish original posts monthly to build entity presence.',
        'Crunchbase — create a verified company profile.',
        'Industry association websites — membership and listing pages build topical authority.',
      ]},
      { type: 'h2', text: 'Pillar 2 — Answer-First Content' },
      { type: 'p', text: 'ChatGPT prefers content that answers questions directly. For each key service page, rewrite the opening so the first paragraph contains a complete, standalone answer to the most common question a potential client would ask. Research shows passages of 134–167 words are cited 2.1× more frequently than longer passages.' },
      { type: 'h2', text: 'Pillar 3 — JSON-LD Schema Markup' },
      { type: 'p', text: "JSON-LD schema tells AI models exactly what your business is, what it does, where it operates, and who runs it. Without schema, the model has to infer these things — and inference creates uncertainty, which reduces citation likelihood. Implement at minimum: LocalBusiness, FAQPage, and Person schema." },
      { type: 'h2', text: 'Expected Timeline' },
      { type: 'p', text: 'If your technical foundation is clean (crawlers not blocked, site fast), you can expect first ChatGPT mentions within 60 days. Consistent, prominent recommendations typically solidify within 4–6 months. The compounding nature of GEO means improvements accelerate over time.' },
    ],
  },
  {
    slug: 'ai-visibility-checker',
    tag: 'Tool',
    tagColor: '#a67ec8',
    title: 'Free AI Visibility Checker — See If AI Recommends You',
    excerpt: 'See if ChatGPT, Google AI Overviews, Perplexity, and Gemini recommend your business. Get your GEO score in 24 hours — free.',
    readTime: '2 min read',
    date: 'June 2026',
    content: [
      { type: 'p', text: 'Most businesses assume they have decent AI visibility. Most are wrong. Our free AI Visibility Checker tests your business across five major AI search platforms — ChatGPT, Google AI Overviews, Perplexity, Gemini, and Microsoft Copilot — and delivers a GEO score (0–100) with specific, actionable findings.' },
      { type: 'h2', text: 'What the Checker Tests' },
      { type: 'list', items: [
        'AI Crawler Accessibility — Is GPTBot, Google-Extended, PerplexityBot, and ClaudeBot allowed on your site? A single misplaced robots.txt rule can make you invisible to all AI platforms.',
        'Schema and Structured Data — Is your LocalBusiness, FAQPage, and Person schema present and valid? Invalid or missing schema is the most common fixable GEO issue.',
        'Content Citability Score — Are your key pages written in answer-first format that AI models are likely to reproduce in their answers?',
        'Brand Authority Signals — How consistently does your brand appear across the authoritative directories and sources that AI models trust?',
        'Per-Platform Visibility — Up to 10 high-intent queries tested on each platform to measure your actual citation rate right now.',
      ]},
      { type: 'h2', text: 'What You Get' },
      { type: 'p', text: 'Within 24 hours of submitting your website URL, industry, and email, you receive a full GEO score report with a breakdown by category, a ranked list of gaps, and a prioritized action plan. The free audit gives you enough to understand exactly where you stand — and what to fix first.' },
      { type: 'h2', text: 'How to Use Your Score' },
      { type: 'list', items: [
        'Score 0–30: Critical gaps. AI models likely cannot find or cite your business. Start with crawler access and schema.',
        'Score 31–55: Foundational issues fixed but content and authority signals are weak. Focus on content restructuring and directory mentions.',
        'Score 56–75: Solid foundation. Refine by query type and target specific platform gaps.',
        'Score 76–100: Strong AI visibility. Focus on maintaining and expanding to new query categories.',
      ]},
      { type: 'stat', text: 'The average business that contacts us has a GEO score below 35 — meaning they are virtually invisible to AI search. After 90 days of our program, the average score rises above 68.' },
      { type: 'p', text: 'Book a free strategy call after receiving your score and we will walk through the findings together — no obligation, no pitch, just clarity on where you stand and what to do next.' },
    ],
  },
];
